[project]
name = "seo-check-os-version"
version = "0.4.0"
description = "Detects and outputs the os version."
authors = [
    {name = "<wminhyuk>", email = "<seoseo1998@gmail.com>"},
]
dependencies = ["stundrg-check-os-ver==0.2.3", "check-os-ver>=0.2.1", "hj-check-os-version==0.2.1", "jacob-os-version-check==0.2.4", "lucas-check-os-ver==0.2.0", "cho-check-os-ver==0.2.3", "nunininu-check-os-ver>=0.3.0"]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[project.urls]
Homepage = "https://github.com/wminhyuk/seo-check-os-version"
Issues = "https://github.com/wminhyuk/seo-check-os-version/issues"

[project.scripts]
seo-hi = "seo_check_os_version.hi:hi"
seo-random = "seo_check_os_version.hi:random_match"

[dependency-groups]
test = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]
